server:
  port: 8080  # gateway port

spring:
  application:
    name: api-gateway  # service name

  config:
    import: "optional:configserver:http://localhost:8888"  # config server

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service  # auth service
          predicates:
            - Path=/api/auth/**  # public endpoints

        - id: zone-service
          uri: lb://zone-service
          predicates:
            - Path=/api/zones/**
          filters:
            - name: Authentication  # JWT check

        - id: sensor-service
          uri: lb://sensor-service
          predicates:
            - Path=/api/sensors/**
          filters:
            - name: Authentication

        - id: crop-service
          uri: lb://crop-inventory-service
          predicates:
            - Path=/api/crops/**
          filters:
            - name: Authentication

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # eureka server
    register-with-eureka: true  # register service
    fetch-registry: true  # get other services

  instance:
    prefer-ip-address: true  # use IP

jwt:
  secret: "a74138c70e93061c2d3d93f941e6295b88fcc694ab2d525d1c001948f6d4ee2a"  # JWT key

management:
  endpoint:
    gateway:
      enabled: true  # enable gateway endpoint
      access: read-only  # read only access

  endpoints:
    web:
      exposure:
        include: health, info, gateway  # exposed endpoints