spring:
  datasource:
    url: jdbc:mysql://localhost:3306/agms_user_db?createDatabaseIfNotExist=true  # database URL
    username: root  # DB username
    password: mysql  # DB password

  jpa:
    hibernate:
      ddl-auto: update  # auto update tables

jwt:
  secret: "a74138c70e93061c2d3d93f941e6295b88fcc694ab2d525d1c001948f6d4ee2a"  # JWT secret key
