server:
  port: 8085

spring:
  application:
    name: auth-service

  config:
    import: "optional:configserver:http://localhost:8888"

  datasource:
    url: jdbc:mysql://localhost:3306/agms_auth_db?createDatabaseIfNotExist=true
    username: mysql
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: "a74138c70e93061c2d3d93f941e6295b88fcc694ab2d525d1c001948f6d4ee2a"