server:
  port: 8083  # service port

spring:
  application:
    name: automation-service  # service name

  datasource:
    url: jdbc:mysql://localhost:3306/agms_automation_db?createDatabaseIfNotExist=true  # DB URL
    username: root  # DB username
    password: mysql  # DB password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # auto update tables
    show-sql: true  # show SQL logs

automation:
  thresholds:
    temperature: 30.0  # temp limit
    humidity: 40.0  # humidity limit

logging:
  level:
    com.agms.automation_service: DEBUG  # debug logs