server:
  port: 8082  # service port

spring:
  application:
    name: sensor-service  # service name

  jackson:
    serialization:
      write-dates-as-timestamps: false  # readable dates

external:
  iot:
    base-url: http://104.211.95.241:8080/api  # IoT API
    username: root  # API username
    password: 1234  # API password

telemetry:
  fetch-interval: 10000  # fetch interval (ms)

logging:
  level:
    com.agms.sensor_telemetry_service: DEBUG  # debug logs