spring:
  application:
    name: zone-service

  config:
    import: "optional:configserver:http://localhost:8888"

  datasource:
    url: jdbc:mysql://localhost:3306/agms_zone_db?createDatabaseIfNotExist=true
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

external:
  iot:
    base-url: http://104.211.95.241:8080/api
    username: sachindu
    password: 1234

auth:
  service:
    base-url: http://localhost:8085/api