server:
  port: 8081  # service port

spring:
  application:
    name: zone-service  # service name

  datasource:
    url: jdbc:mysql://localhost:3306/agms_zone_db?createDatabaseIfNotExist=true  # DB URL
    username: root  # DB username
    password: mysql  # DB password

  jpa:
    hibernate:
      ddl-auto: update  # auto update tables
    show-sql: true  # show SQL logs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # eureka server

external:
  iot:
    base-url: http://104.211.95.241:8080/api  # IoT API